global:
  scrape_interval:     60s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: pronestheus
    static_configs:
      - targets: ['pronestheus:9777']
    