image: 
  repository: registry.gitlab.com/grdl/pronestheus
  tag: latest

# Based on NodeExporter Helm chart (https://github.com/helm/charts/blob/master/stable/prometheus-node-exporter/values.yaml)
service:
  type: ClusterIP
  port: 9999
  targetPort: 9999
  nodePort:
  annotations:
    prometheus.io/scrape: "true"

nest:
  token: 
  url: https://developer-api.nest.com/devices/thermostats

openWeatherMap:
  token:
  url: http://api.openweathermap.org/data/2.5/weather
  location: "2759794" # That's Amsterdam
